main/urls.py
from django.urls import path
from .import views
urlpatterns = [
   path('',views.index,name='index')

]

poll_app/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('main.urls')),
    path('polls/',include('polls.urls'))

]

polls/urls.py
from django.urls import path
from . import views
app_name='polls'
urlpatterns = [
   path('',views.index,name='index'),
   path('<int:question_id>/',views.detail,name='detail'),
   path('<int:question_id>/results/',views.results,name='results'),
   path('<int:question_id>/vote/',views.vote,name='vote'),
   path('resultsdata/<str:obj>/', views.resultsData, name="resultsdata"),
]

main/models.py
from django.db import models

# Create your models here.

polls/models.py
import datetime
from django.db import models
from django.utils import timezone
# Create your models here.
class Question(models.Model):
    question_text=models.CharField(max_length=200)
    pub_date=models.DateTimeField('date published')
    def was_published_recently(self):
        return self.pub_date >= timezone.now()-datetime.timedelta(days=1)
    def __str__(self):
        return self.question_text

class Choice(models.Model):
    question=models.ForeignKey(Question,on_delete=models.CASCADE)
    choice_text=models.CharField(max_length=200)
    votes=models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text

main/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request,'main/index.html')

polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import Http404, HttpResponseRedirect
from django.urls import reverse
from django.http import JsonResponse

from .models import Question,Choice
# Create your views here.
def index(request):
    latest_question_list=Question.objects.order_by('-pub_date')[:5]
    context={'latest_question_list':latest_question_list}
    return render(request,'polls/index.html',context)
def detail(request,question_id):
    try:
        question=Question.objects.get(pk=question_id)
    except Question.DoesNotExist:
        raise Http404("Question does not exist")
    return render(request,'polls/detail.html',{'question':question})
def results(request,question_id):
    question=get_object_or_404(Question,pk=question_id)
    return render(request,'polls/results.html',{'question':question})
def vote(request,question_id):
    question=get_object_or_404(Question,pk=question_id)
    try:
        selected_choice=question.choice_set.get(pk=request.POST['choice'])
    except (KeyError,Choice.DoesNotExist):
        return render(request,'polls/detail.html',{
            'question':question,
            'error_message':"You didn't select a choice"
        })
    else:
        selected_choice.votes+=1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results',args=(question.id,)))

def resultsData(request, obj):
    votedata = []

    question = Question.objects.get(id=obj)
    votes = question.choice_set.all()

    for i in votes:
        votedata.append({i.choice_text:i.votes})

    print(votedata)
    return JsonResponse(votedata, safe=False)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Poll_App {% block title %}{% endblock%}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"  crossorigin="anonymous">


</head>
<body>
<!--    NAVBAR-->
   {% include 'navbar.html' %}
    <div class="container">
        <div class="row">
            <div class="col-md-6 m-auto">
                {% block content %}
                {% endblock%}
            </div>
        </div>
    </div>
  
  <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"  crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" crossorigin="anonymous"></script>
</body>
</html>

templates/main/index.html
<!DOCTYPE html>
<html lang="en">
<head>
   <style>
     .btn-dark {
    background-image: linear-gradient(#4568DC,#B06AB3);
    }
    .btn-dark:hover{
    background-image: linear-gradient(#5f2c82,#49a09d);
    transform: scale(1.2);
    transition:0.4s;
    }
    .btn.btn-dark {
    border-radius: 20px;
    }
    </style>
    
</head>
<body>
{% extends 'base.html' %}
{% block content %}
<div class="card text-center">
    <div class="card-body">
        <h1>Welcome to Poll App</h1>
        <p>This is Django Poll App</p>
        <a class="btn btn-dark" href="{% url 'polls:index' %}">View Available Polls</a>
    </div>
</div>
</body>
{% endblock %}
</html>

templates/navbar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <style>
     .bg-light {
    background-color: #7579e7 !important;
      }
        .navbar-light .navbar-brand {
    color: #FFF;
            font-weight:bold;
            margin-left: 20px;
    }
        .btn-outline-success{
            color: #FFFFFF;
        }
   
    </style>
</head>
<body>
<nav class="navbar navbar-light bg-light mb-5">
  <a class="navbar-brand">POLL_APP</a>
</nav>
</body>
</html>

templates/polls/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
</head>
<body>
  {% extends 'base.html' %}
  {% block content %}
  <a class="btn btn-outline-secondary btn-sm nb-3" href="{% url 'polls:index'%}">Back to polls</a>
  <h1 class="text-center mb-3">{{question.question_text}}</h1>
<!--  <p>{{question.pub_date}}</p>-->
  <blockquote class="blockquote">
  <p class="mb-0">Publication Date</p>
  <footer class="blockquote-footer"><cite title="Source Title">{{question.pub_date}}</cite></footer>
</blockquote>

  {% if error_message %}
  <p class="alert alert-danger"><strong>{{ error_message}}</strong></p>
  {% endif %}

  <form action="{% url 'polls:vote' question.id %}" method="post">
      {% csrf_token %}
      {% for choice in question.choice_set.all%}
      <div class="form-check">
          <input
                  type="radio"
                  name="choice"
                  class="form-check-input"
                  id="choice{{ forloop.counter }}"
                  value="{{choice.id}}"
                  />
          <label>{{choice.choice_text}}</label>
      </div>
      {% endfor %}
      <input type="submit" value="Vote" class="btn btn-success btn-block mt-3">
  </form>
  {% endblock %}
</body>
</html>

templates/polls/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
</head>
<body>
  {% extends 'base.html' %}
  {% block content %}
  <h1 class="mb-3">Poll Questions</h1>
  {% if latest_question_list%}
  {% for question in latest_question_list %}
  <div class="card mb-3">
      <div class="card-body">
          <p class="lead">{{question.question_text}}</p>
          <a href="{% url 'polls:detail' question.id %}" class="btn btn-primary btn-sm">Vote Now</a>
          <a href="{% url 'polls:results' question.id%}" class="btn btn-secondary btn-sm">Results</a>
      </div>
  </div>
  {% endfor%}
  {% else %}
  <p>No polls available</p>
  {% endif %}
  {% endblock %}
</body>
</html>

templates/polls/results.html
<!DOCTYPE html>
<html lang="en">
<head>
    <style>
    .btn-secondary{
    background-color:#46B3E6 !important;
    opacity:0.9;
    border-color: #46B3E6;
    }
    .btn-secondary:hover{
    opacity:1;
    }
     .btn-dark {
     background-color:#1E56A0 !important;
     opacity:0.9;
    }
    .btn-dark:hover{
    opacity:1;
    }
    </style>
</head>
<body>
{% extends 'base.html' %}
{% block content %}
<script src="https://cdn.zingchart.com/zingchart.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<h1 class="text-center">{{question.question_text}}</h1>
<ul class="list-group mb-5">
    {% for choice in question.choice_set.all%}
    <li class="list-group-item">{{choice.choice_text}} <span class="badge badge-success float-right">{{choice.votes}} vote{{choice.votes | pluralize }}</span></li>
    {% endfor %}
</ul>

<div id="myChart"></div>
<a class="btn btn-secondary back" href="{% url 'polls:index'%}">Back to Polls</a>
<a class="btn btn-dark" href="{% url 'polls:detail' question.id%}">Vote Again</a>
<script>
      var state ={
		'items':[],
		'values':[],
	}

	var objId = "{{question.id}}"

	var dataURL = `/polls/resultsdata/${objId}/`
	$.ajax({
		method:'GET',
		url:dataURL,
		success:function(response){
			console.log('RESPONSE:', response)
			for (var i in response){

				var key = Object.keys(response[i])[0]
				var value = Object.values(response[i])[0]

				state.items.push(key)
				state.values.push(value)
			}

			console.log('STATE:', state)
			buildChart()

		}
	})

	function buildChart(){
			var chartData = {
			"type":"bar",
			"scale-x":{
				"values":state.items
			},
			"series":[
				{
					"values":state.values
				}
			]
		}


		zingchart.render({
		  id: "myChart",
		  data: chartData,
		});
	}
</script>
{% endblock %}
</body>
</html>